In [1]:
import sqlite3

import pandas as pd

In [2]:
# connect to db and showing available tables inside
db_path = r"D:\2026\MLOps-Qafza-2026\database\olist.db"

conn = sqlite3.connect(db_path)

query = """
SELECT name
FROM sqlite_master
WHERE type = 'table'
ORDER BY name;
"""

tables = pd.read_sql_query(query, conn)
display(tables)

                                 name
0               agg_olist_order_items
1            agg_olist_order_payments
2             agg_olist_order_reviews
3                           ml_orders
4                     olist_customers
5                   olist_geolocation
6                   olist_order_items
7                olist_order_payments
8                 olist_order_reviews
9                        olist_orders
10                     olist_products
11                      olist_sellers
12  product_category_name_translation

In [3]:
# read and view the table "ml_orders"
query = '''
select * from ml_orders
'''

ml_orders = pd.read_sql_query(query, conn)
display(ml_orders)
print('the shape of ml_orders: ', ml_orders.shape)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,number_of_items,total_freight_value,total_price,number_of_sellers,number_of_products,number_of_payments,total_payment_value,number_of_payment_types,max_payment_installments
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,8.72,29.99,1.0,1.0,3.0,38.71,2.0,1.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1.0,22.76,118.70,1.0,1.0,1.0,141.46,1.0,1.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1.0,19.22,159.90,1.0,1.0,1.0,179.12,1.0,3.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,1.0,27.20,45.00,1.0,1.0,1.0,72.20,1.0,1.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,1.0,8.72,19.90,1.0,1.0,1.0,28.62,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00,1.0,13.08,72.00,1.0,1.0,1.0,85.08,1.0,3.0
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,1.0,20.10,174.90,1.0,1.0,1.0,195.00,1.0,3.0
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,1.0,65.02,205.99,1.0,1.0,1.0,271.01,1.0,5.0
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,2.0,81.18,359.98,1.0,1.0,1.0,441.16,1.0,4.0
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,1.0,18.36,68.50,1.0,1.0,1.0,86.86,1.0,1.0

the shape of ml_orders:  (99441, 17)

In [ ]:
# check for the missed dates in 'order_delivered_customer_date' or 'order_estimated_delivery_date'
ml_orders[['order_delivered_customer_date', 'order_estimated_delivery_date']].isna().sum()

order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [ ]:
# simple query for the missed dates as df
ml_orders[
    ml_orders['order_delivered_customer_date'].isna() |
    ml_orders['order_estimated_delivery_date'].isna()
][[
    'order_id',
    'order_status',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]]

,order_id,order_status,order_delivered_customer_date,order_estimated_delivery_date
6,136cce7faa42fdb2cefd53fdc79a6098,invoiced,NaN,2017-05-09 00:00:00
44,ee64d42b8cf066f35eac1cf57de1aa85,shipped,NaN,2018-06-28 00:00:00
103,0760a852e4e9d89eb77bf631eaaf1c84,invoiced,NaN,2018-08-21 00:00:00
128,15bed8e2fec7fdbadb186b57c46c92f2,processing,NaN,2017-10-03 00:00:00
154,6942b8da583c2f9957e990d028607019,shipped,NaN,2018-02-07 00:00:00
...,...,...,...,...
99283,3a3cddda5a7c27851bd96c3313412840,canceled,NaN,2018-10-01 00:00:00
99313,e9e64a17afa9653aacf2616d94c005b8,processing,NaN,2018-02-06 00:00:00
99347,a89abace0dcc01eeb267a9660b5ac126,canceled,NaN,2018-09-27 00:00:00
99348,a69ba794cc7deb415c3e15a0a3877e69,unavailable,NaN,2017-09-15 00:00:00
99415,5fabc81b6322c8443648e1b21a6fef21,unavailable,NaN,2017-10-23 00:00:00

In [12]:
# how many orders with missed dates
missed_delivery_dates = ml_orders[
    ml_orders['order_delivered_customer_date'].isna() |
    ml_orders['order_estimated_delivery_date'].isna()
].shape[0]
missed_delivery_dates

2965

In [13]:
# how many orders without missed dates
not_missed_delivery_dates = ml_orders[
    ml_orders['order_delivered_customer_date'].notna() &
    ml_orders['order_estimated_delivery_date'].notna()
].shape[0]
not_missed_delivery_dates

96476

In [16]:
# the percent of missed and not missed delivery date from overall row data
missed_delivery_dates_percent = (missed_delivery_dates / ml_orders.shape[0]) * 100
not_missed_delivery_dates_percent = (not_missed_delivery_dates / ml_orders.shape[0]) * 100

print('missed_delivery_dates_percent:', missed_delivery_dates_percent)
print('not_missed_delivery_dates_percent: ', not_missed_delivery_dates_percent)

missed_delivery_dates_percent: 2.981667521444877
not_missed_delivery_dates_percent:  97.01833247855512

In [7]:
# what is the order status for missed delivery dates ??
ml_orders.loc[ml_orders['order_delivered_customer_date'].isna(), 'order_status'].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [17]:
# what is the order status for not missed delivery dates ??
ml_orders.loc[ml_orders['order_delivered_customer_date'].notna(), 'order_status'].value_counts()

order_status
delivered    96470
canceled         6
Name: count, dtype: int64

In [ ]:
# there is 6 orders having delivery date and cancelled (seem cancelled after delivered ??)
ml_orders.loc[(ml_orders['order_delivered_customer_date'].notna()) & (ml_orders['order_status'] == 'canceled')]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,number_of_items,total_freight_value,total_price,number_of_sellers,number_of_products,number_of_payments,total_payment_value,number_of_payment_types,max_payment_installments
2921,1950d777989f6a877539f53795b4c3c3,1bccb206de9f0f25adc6871a1bcf77b2,canceled,2018-02-19 19:48:52,2018-02-19 20:56:05,2018-02-20 19:57:13,2018-03-21 22:03:51,2018-03-09 00:00:00,1.0,14.10,29.99,1.0,1.0,1.0,44.09,1.0,2.0
8791,dabf2b0e35b423f94618bf965fcb7514,5cdec0bb8cbdf53ffc8fdc212cd247c6,canceled,2016-10-09 00:56:52,2016-10-09 13:36:58,2016-10-13 13:36:59,2016-10-16 14:36:59,2016-11-30 00:00:00,2.0,30.42,109.80,1.0,2.0,1.0,140.22,1.0,2.0
58266,770d331c84e5b214bd9dc70a10b829d0,6c57e6119369185e575b36712766b0ef,canceled,2016-10-07 14:52:30,2016-10-07 15:07:10,2016-10-11 15:07:11,2016-10-14 15:07:11,2016-11-29 00:00:00,1.0,14.03,249.90,1.0,1.0,1.0,263.93,1.0,2.0
59332,8beb59392e21af5eb9547ae1a9938d06,bf609b5741f71697f65ce3852c5d2623,canceled,2016-10-08 20:17:50,2016-10-09 14:34:30,2016-10-14 22:45:26,2016-10-19 18:47:43,2016-11-30 00:00:00,1.0,11.23,99.99,1.0,1.0,1.0,111.22,1.0,5.0
92636,65d1e226dfaeb8cdc42f665422522d14,70fc57eeae292675927697fe03ad3ff5,canceled,2016-10-03 21:01:41,2016-10-04 10:18:57,2016-10-25 12:14:28,2016-11-08 10:58:34,2016-11-25 00:00:00,1.0,14.11,21.50,1.0,1.0,1.0,35.61,1.0,1.0
94399,2c45c33d2f9cb8ff8b1c86cc28c11c30,de4caa97afa80c8eeac2ff4c8da5b72e,canceled,2016-10-09 15:39:56,2016-10-10 10:40:49,2016-10-14 10:40:50,2016-11-09 14:53:50,2016-12-08 00:00:00,1.0,18.51,135.00,1.0,1.0,1.0,153.51,1.0,3.0

In [22]:
# delete the orders which having no delivery date as its less than 3%
ml_orders = ml_orders[
    ml_orders["order_delivered_customer_date"].notna() &
    ml_orders["order_estimated_delivery_date"].notna()
].copy()  # .copy() → creates a clean independent DataFrame

ml_orders.shape

(96476, 17)

Create the delivery label  
label = 1  # Late:     when the actual delivery date is after the estimated date.  
label = 0  # not Late: when the actual delivery date is on time or before

In [23]:
#  creating the delivery label considering the missed delivery dates removed
# np.where(condition, value_if_true, value_if_false)
import numpy as np

ml_orders['is_late_label'] = np.where(
    ml_orders['order_delivered_customer_date'] >
    ml_orders['order_estimated_delivery_date'],
    1,
    0
)

In [24]:
# Check real orders manually
# manual spot-check of 10 random orders to see whether 'is_late' label is correct.
# random_state=42: use 42 as the seed to determine which 10 rows (if need the same random values again, use the same random_state number)
check = ml_orders[
    [
        "order_id",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
        "is_late_label"
    ]
].sample(10, random_state=42)  # Randomly select 10 orders and the random selection reproducible (if run it again, will get the same 10 orders)

check

,order_id,order_delivered_customer_date,order_estimated_delivery_date,is_late_label
22500,c58cff333993bb6b7161d7ec1350eef3,2018-04-06 02:32:49,2018-04-18 00:00:00,0
68941,87673b5ccb20de0a91c28cc461105d76,2018-05-23 15:28:28,2018-05-30 00:00:00,0
23988,80b430d0029bb33110ac31d60e87e0b8,2017-12-07 18:43:46,2017-12-27 00:00:00,0
31303,580603672a21252f21fa8a8b4ca85986,2018-04-26 17:44:27,2018-05-08 00:00:00,0
36131,c09f32e7ba9b4a134455b36eeff8fff3,2018-04-13 17:32:07,2018-04-24 00:00:00,0
58330,462240cb1ec4e5db517e73fff57ebfc0,2017-12-14 18:56:14,2017-12-20 00:00:00,0
95960,5bc2a7b8f0817443a86b69461e742cc9,2018-01-12 21:59:18,2018-02-01 00:00:00,0
56131,4ef8f514f95bb0a41f58965ea04e7027,2017-05-26 15:59:47,2017-06-07 00:00:00,0
56750,587904dc1c873ebfb6078160b4819d8e,2017-12-06 19:43:34,2017-12-15 00:00:00,0
92212,29c3b79aace1b72a82b1232bf494e16f,2018-04-28 15:51:50,2018-01-24 00:00:00,1

In [ ]:
# what is the count for late and not late orders
ml_orders["is_late_label"].value_counts()

is_late_label
0    88649
1     7827
Name: count, dtype: int64

In [ ]:
# what is the percent for late and not late orders
ml_orders["is_late_label"].value_counts(normalize=True) * 100

is_late_label
0    91.887101
1     8.112899
Name: proportion, dtype: float64

In [27]:
# Look at class distribution
class_distribution = (
    ml_orders["is_late_label"]
    .value_counts()
    .rename(index={0: "On time", 1: "Late"})
    .to_frame("count") 
    # Convert the Series to a DataFrame:
    # value_counts() normally returns a Series. 
    # so, .to_frame("count") converts it into a DataFrame and names the column "count".
)

class_distribution["percentage"] = (
    class_distribution["count"]
    / class_distribution["count"].sum()
    * 100
)

class_distribution

               count  percentage
is_late_label
On time        88649   91.887101
Late            7827    8.112899

In [32]:
# Decide whether there is class imbalance (Class imbalance means that target classes have very different numbers of observations.)
# check whether one class is much larger than the other
counts = ml_orders["is_late_label"].value_counts()

majority = counts.max()
minority = counts.min()

imbalance_ratio = majority / minority

print(f"Majority class: {majority:,}")
print(f"Minority class: {minority:,}")
print(f"Imbalance ratio: {imbalance_ratio:.2f}:1")

Majority class: 88,649
Minority class: 7,827
Imbalance ratio: 11.33:1

In [33]:
ml_orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,number_of_items,total_freight_value,total_price,number_of_sellers,number_of_products,number_of_payments,total_payment_value,number_of_payment_types,max_payment_installments,is_late_label
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,8.72,29.99,1.0,1.0,3.0,38.71,2.0,1.0,0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1.0,22.76,118.70,1.0,1.0,1.0,141.46,1.0,1.0,0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1.0,19.22,159.90,1.0,1.0,1.0,179.12,1.0,3.0,0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,1.0,27.20,45.00,1.0,1.0,1.0,72.20,1.0,1.0,0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,1.0,8.72,19.90,1.0,1.0,1.0,28.62,1.0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00,1.0,13.08,72.00,1.0,1.0,1.0,85.08,1.0,3.0,0
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,1.0,20.10,174.90,1.0,1.0,1.0,195.00,1.0,3.0,0
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,1.0,65.02,205.99,1.0,1.0,1.0,271.01,1.0,5.0,0
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,2.0,81.18,359.98,1.0,1.0,1.0,441.16,1.0,4.0,0
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,1.0,18.36,68.50,1.0,1.0,1.0,86.86,1.0,1.0,0

In [34]:
# save ml_orders_labled into the db
ml_orders.to_sql('ml_orders_labled', conn, if_exists="replace", index=False)

96476

In [35]:
# display the names for all tables inside the db
query = """
SELECT name
FROM sqlite_master
WHERE type = 'table'
ORDER BY name;
"""

tables = pd.read_sql_query(query, conn) 
tables

                                 name
0               agg_olist_order_items
1            agg_olist_order_payments
2             agg_olist_order_reviews
3                           ml_orders
4                    ml_orders_labled
5                     olist_customers
6                   olist_geolocation
7                   olist_order_items
8                olist_order_payments
9                 olist_order_reviews
10                       olist_orders
11                     olist_products
12                      olist_sellers
13  product_category_name_translation

In [37]:
# reading 'ml_orders_labled' table from db and validate the rows count 
query = ''' 
select * from ml_orders_labled
'''
df = pd.read_sql_query(query, conn)
display(df)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,number_of_items,total_freight_value,total_price,number_of_sellers,number_of_products,number_of_payments,total_payment_value,number_of_payment_types,max_payment_installments,is_late_label
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,8.72,29.99,1.0,1.0,3.0,38.71,2.0,1.0,0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1.0,22.76,118.70,1.0,1.0,1.0,141.46,1.0,1.0,0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1.0,19.22,159.90,1.0,1.0,1.0,179.12,1.0,3.0,0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,1.0,27.20,45.00,1.0,1.0,1.0,72.20,1.0,1.0,0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,1.0,8.72,19.90,1.0,1.0,1.0,28.62,1.0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96471,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00,1.0,13.08,72.00,1.0,1.0,1.0,85.08,1.0,3.0,0
96472,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,1.0,20.10,174.90,1.0,1.0,1.0,195.00,1.0,3.0,0
96473,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,1.0,65.02,205.99,1.0,1.0,1.0,271.01,1.0,5.0,0
96474,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,2.0,81.18,359.98,1.0,1.0,1.0,441.16,1.0,4.0,0
96475,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,1.0,18.36,68.50,1.0,1.0,1.0,86.86,1.0,1.0,0