Notebook 5 — Feature engineering
-------

In [4]:
import sqlite3

import pandas as pd

In [ ]:
from src.features.feature_selection import select_model_features

In [5]:
# connect to db and showing available tables inside
db_path = r"D:\2026\MLOps-Qafza-2026\database\olist.db"

conn = sqlite3.connect(db_path)

query = """
SELECT name
FROM sqlite_master
WHERE type = 'table'
ORDER BY name;
"""

tables = pd.read_sql_query(query, conn)
display(tables)

                                 name
0               agg_olist_order_items
1            agg_olist_order_payments
2             agg_olist_order_reviews
3                           ml_orders
4                    ml_orders_labled
5                     olist_customers
6                   olist_geolocation
7                   olist_order_items
8                olist_order_payments
9                 olist_order_reviews
10                       olist_orders
11                     olist_products
12                      olist_sellers
13  product_category_name_translation
14                        testing_set
15                       training_set
16               updated_training_set
17                     validation_set

Data view: 
-----

In [6]:
# reading validation_set and testing_set
validation_set = pd.read_sql_query('select * from validation_set', conn)
testing_set = pd.read_sql_query('select * from testing_set', conn)

In [7]:
# read and view the table "updated_training_set"
query = '''
select * from updated_training_set
'''

updated_training_set = pd.read_sql_query(query, conn)
display(updated_training_set)
print('the shape of updated_training_set: ', updated_training_set.shape)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,number_of_items,total_freight_value,...,delivery_difference_days,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,seller_state,seller_zip_code_prefix,seller_count,customer_seller_same_state,zip_prefix_difference
0,2bedc0d7231e504d0476c606108e7e73,fff93c1da78dafaaa304ff032abc6205,delivered,2018-06-13 01:57:22,2018-06-13 02:59:41,2018-06-18 14:01:00,2018-06-21 11:56:46,2018-07-11 00:00:00,3.0,43.60,...,-19.502245,d8dc373219d0f95053c8d65df85a7f1c,14802,araraquara,SP,SP,9360.0,1,1,5442.0
1,202c632ebb14ebfabad48f43c9a9f166,d7263dd40ab3973760e65588299bfaa8,delivered,2018-05-14 12:55:16,2018-05-14 13:17:09,2018-05-14 15:12:00,2018-05-22 23:16:46,2018-05-28 00:00:00,1.0,15.41,...,-5.030023,4acc588accb6e7b5b57fc8814dbfb76c,93222,sapucaia do sul,RS,RS,99500.0,1,1,6278.0
2,df9deeb3f35f5f1f50697012b7bab129,22f376753863f196880ee0a11aead3e1,delivered,2018-01-13 13:36:23,2018-01-16 04:31:07,2018-01-19 01:58:40,2018-02-02 01:06:08,2018-03-02 00:00:00,1.0,58.54,...,-27.954074,f170c6e04c4cdf9219fc5c669b10f506,29901,linhares,ES,RO,76900.0,1,0,46999.0
3,1129997904eb031a05d781b6179078d7,f740e6e44d74fb1e93f1bcd947925230,delivered,2018-01-10 15:54:11,2018-01-10 16:09:53,2018-01-11 23:03:37,2018-01-12 22:37:36,2018-01-29 00:00:00,1.0,9.37,...,-16.057222,73bbeacd7793ce272e6276558e47f2e2,18070,sorocaba,SP,SP,1026.0,1,1,17044.0
4,b8ee80bb6d575240f0b5f9f87987be6d,d3bc1fd607f5e867e30371619d28a55b,delivered,2018-06-11 20:22:26,2018-06-11 20:40:57,2018-06-13 13:37:00,2018-07-05 15:58:26,2018-06-29 00:00:00,1.0,68.45,...,6.665579,934157f44075d9ca396f27f72c99a338,29325,itaoca,ES,SP,3821.0,1,0,25504.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67528,6a1dff28da32815c94da401e19d2a7f8,29251d6a551cedc7040b152221744460,delivered,2017-03-21 11:33:31,2017-03-21 11:33:31,2017-03-27 14:13:02,2017-03-31 15:34:11,2017-04-13 00:00:00,1.0,10.96,...,-12.351262,95f270e7d1d60bde8031dc0c058558e0,15745,paranapua,SP,SP,13820.0,1,1,1925.0
67529,31874b1728b2dc2adbd7ac767892fce0,daf22b7353d8e5021df9894b32dd6b45,delivered,2018-06-02 08:47:12,2018-06-02 08:55:27,2018-06-04 13:49:00,2018-06-26 18:50:45,2018-07-17 00:00:00,1.0,51.13,...,-20.214757,bfe6b5289dd1cec948d3714ae5453392,49870,itabi,SE,SP,2252.0,1,0,47618.0
67530,d8f92d7e898a1027a0957b82f58ddbc4,3278f0116538282732803d2b35a9fbd6,delivered,2018-08-21 20:10:39,2018-08-21 20:25:19,2018-08-22 12:27:00,2018-08-23 18:58:41,2018-08-24 00:00:00,1.0,7.65,...,-0.209248,edd286dff982df97e304f16bc5c586b5,9840,sao bernardo do campo,SP,SP,5849.0,1,1,3991.0
67531,35011b1b3211ea7c58a699e4b8bfe93d,9c9da709db4d73a4b732e11026252c3c,delivered,2017-06-22 15:00:45,2017-06-22 15:10:20,2017-06-26 15:39:44,2017-07-03 16:54:58,2017-07-05 00:00:00,1.0,12.48,...,-1.295162,0c45dff0741b5a083effb76c24e8c3bd,13025,campinas,SP,SP,13419.0,1,1,394.0
67532,64b281751527cf3da5d9eb68c785cedf,aa213e6f66f6c3c075e569427d8344ce,delivered,2018-04-24 14:27:15,2018-04-24 18:05:54,2018-04-24 23:55:40,2018-05-09 16:37:38,2018-05-24 00:00:00,1.0,52.64,...,-14.307199,57809944fa2fb381c6ed02a36c046676,53429,paulista,PE,MG,37564.0,1,0,15865.0

the shape of updated_training_set:  (67533, 34)

In [8]:
updated_training_set_columns = pd.read_sql_query('PRAGMA table_info("updated_training_set")', conn)
display(updated_training_set_columns)

    cid                           name       type  notnull dflt_value  pk
0     0                       order_id       TEXT        0       None   0
1     1                    customer_id       TEXT        0       None   0
2     2                   order_status       TEXT        0       None   0
3     3       order_purchase_timestamp  TIMESTAMP        0       None   0
4     4              order_approved_at  TIMESTAMP        0       None   0
5     5   order_delivered_carrier_date  TIMESTAMP        0       None   0
6     6  order_delivered_customer_date  TIMESTAMP        0       None   0
7     7  order_estimated_delivery_date  TIMESTAMP        0       None   0
8     8                number_of_items       REAL        0       None   0
9     9            total_freight_value       REAL        0       None   0
10   10                    total_price       REAL        0       None   0
11   11              number_of_sellers       REAL        0       None   0
12   12             number_of_products       REAL        0       None   0
13   13             number_of_payments       REAL        0       None   0
14   14            total_payment_value       REAL        0       None   0
15   15        number_of_payment_types       REAL        0       None   0
16   16       max_payment_installments       REAL        0       None   0
17   17                  is_late_label    INTEGER        0       None   0
18   18                  purchase_year    INTEGER        0       None   0
19   19                 purchase_month    INTEGER        0       None   0
20   20             purchase_dayofweek    INTEGER        0       None   0
21   21                  purchase_hour    INTEGER        0       None   0
22   22           actual_delivery_days       REAL        0       None   0
23   23        estimated_delivery_days       REAL        0       None   0
24   24       delivery_difference_days       REAL        0       None   0
25   25             customer_unique_id       TEXT        0       None   0
26   26       customer_zip_code_prefix    INTEGER        0       None   0
27   27                  customer_city       TEXT        0       None   0
28   28                 customer_state       TEXT        0       None   0
29   29                   seller_state       TEXT        0       None   0
30   30         seller_zip_code_prefix       REAL        0       None   0
31   31                   seller_count    INTEGER        0       None   0
32   32     customer_seller_same_state    INTEGER        0       None   0
33   33          zip_prefix_difference       REAL        0       None   0

Identify columns that must not be used
------

In [9]:
target = "is_late_label"

future_columns = [
    "order_delivered_customer_date",
    "order_delivered_carrier_date",
    "order_estimated_delivery_date"
]

# estimated_days = (
#     order_estimated_delivery_date - order_purchase_timestamp
# )

Create useful date features
--------

In [10]:
# convert date columns to date type
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    updated_training_set[col] = pd.to_datetime(updated_training_set[col])
    validation_set[col] = pd.to_datetime(validation_set[col])
    testing_set[col] = pd.to_datetime(testing_set[col])

In [ ]:
# this is replaced by the next cell

# create date features function    
# def create_date_features(df):
    
#     df = df.copy()
    
#     # Purchase date
#     df["purchase_year"] = df["order_purchase_timestamp"].dt.year
#     df["purchase_month"] = df["order_purchase_timestamp"].dt.month
#     df["purchase_day"] = df["order_purchase_timestamp"].dt.day
#     df["purchase_dayofweek"] = df["order_purchase_timestamp"].dt.dayofweek
#     df["purchase_hour"] = df["order_purchase_timestamp"].dt.hour
    
#     # Estimated delivery duration
#     df["estimated_delivery_days"] = (
#         df["order_estimated_delivery_date"]
#         - df["order_purchase_timestamp"]
#     ).dt.total_seconds() / 86400
    
#     # Approval delay
#     df["approval_delay_hours"] = (
#         df["order_approved_at"]
#         - df["order_purchase_timestamp"]
#     ).dt.total_seconds() / 3600
    
#     return df

In [11]:
# Modofication for Task 3

import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

sys.path.insert(
    0,
    str(PROJECT_ROOT / "src")
)


from features.feature_engineering import create_date_features

In [12]:
# apply the same feature engineering function to all splits:
# The function itself does not learn anything from the data, so it is safe to apply independently.
train_fe = create_date_features(updated_training_set)

val_fe = create_date_features(validation_set)

test_fe = create_date_features(testing_set)

Handle missing values
------

In [13]:
# X_train = train_fe.drop(columns=[target])
# y_train = train_fe[target]

# X_val = val_fe.drop(columns=[target])
# y_val = val_fe[target]

# X_test = test_fe.drop(columns=[target])
# y_test = test_fe[target]

import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

print("Project root:", PROJECT_ROOT)

X_train = select_model_features(train_fe, target)
y_train = train_fe[target]

X_val = select_model_features(val_fe, target)
y_val = val_fe[target]

X_test = select_model_features(test_fe, target)
y_test = test_fe[target]

Project root: d:\Zain MS\Programming\Machine Learning\Qafza_MLOps\closed Tasks\Task_3\olist-mlops

In [ ]:
from src.preprocessing.preprocessor import (
    build_preprocessor,
    get_feature_columns,
)

print("Preprocessing functions imported OK")

In [ ]:
numeric_columns, categorical_columns = get_feature_columns(
    X_train
)

preprocessor = build_preprocessor(
    numeric_columns,
    categorical_columns,
)

In [2]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print("Project root:", PROJECT_ROOT)

Project root: d:\Zain MS\Programming\Machine Learning\Qafza_MLOps\closed Tasks\Task_3\olist-mlops

In [3]:
from src.features.feature_selection import select_model_features

print("Feature selection import OK")

Feature selection import OK

In [14]:
print("X_train shape:", X_train.shape)

print("\nLeakage columns still present:")
print([
    col for col in [
        "order_delivered_customer_date",
        "order_delivered_carrier_date",
        "actual_delivery_days",
        "delivery_difference_days",
    ]
    if col in X_train.columns
])

print("\nRequired engineered features:")
print([
    col for col in [
        "purchase_year",
        "purchase_month",
        "purchase_day",
        "purchase_dayofweek",
        "purchase_hour",
        "estimated_delivery_days",
        "approval_delay_hours",
    ]
    if col in X_train.columns
])

X_train shape: (67533, 28)

Leakage columns still present:
[]

Required engineered features:
['purchase_year', 'purchase_month', 'purchase_day', 'purchase_dayofweek', 'purchase_hour', 'estimated_delivery_days', 'approval_delay_hours']

In [ ]:
# identify numerical and categorical columns.
# select column types:

# numeric_columns = X_train.select_dtypes(
#     include=["number"]
# ).columns.tolist()

# categorical_columns = X_train.select_dtypes(
#     include=["object", "category", "bool", "string"]
# ).columns.tolist()

In [16]:
from src.preprocessing.preprocessor import (
    build_preprocessor,
    get_feature_columns,
)

print("Preprocessing functions imported OK")

Preprocessing functions imported OK

In [18]:
# there was a missed column in val & test sets and solved :
    # actual_delivery_days
    # delivery_difference_days
    # customer_zip_code_prefix
    # seller_zip_code_prefix
    # seller_count
    # customer_seller_same_state
    # zip_prefix_difference

# Columns in X_train but missing from X_val
missing_in_val = set(X_train.columns) - set(X_val.columns)

# Columns in X_train but missing from X_test
missing_in_test = set(X_train.columns) - set(X_test.columns)

print("Missing in validation:")
print(missing_in_val)

print("\nMissing in test:")
print(missing_in_test)

Missing in validation:
set()

Missing in test:
set()

In [19]:
print("Train shape:", X_train.shape)
print("Validation shape:", X_val.shape)
print("Test shape:", X_test.shape)

print("\nTrain columns:", len(X_train.columns))
print("Validation columns:", len(X_val.columns))
print("Test columns:", len(X_test.columns))

Train shape: (67533, 28)
Validation shape: (14471, 28)
Test shape: (14472, 28)

Train columns: 28
Validation columns: 28
Test columns: 28

In [20]:
print(set(X_train.columns) - set(X_val.columns))
print(set(X_train.columns) - set(X_test.columns))

set()
set()

In [21]:
# For numerical columns, a good starting point is median imputation.
from sklearn.impute import (
    SimpleImputer,  # SimpleImputer is used to handle missing values dataset.
)

# can use SimpleImputer to replace missing values with:
    # Mean → average value
    # Median → middle value
    # Most frequent → most common value
    # Constant → a fixed value such as 0 or "Unknown"
# SimpleImputer = a tool that fills missing values before training machine learning model.

# Create median imputer , creates an imputer object called numeric_imputer.
    # SimpleImputer → Scikit-learn tool for handling missing values (NaN).
    # strategy="median" → Tells it to replace missing numerical values with the median of that column.
    # numeric_imputer → variable name for this imputer.
numeric_imputer = SimpleImputer(strategy="median")
# At this point, it has not calculated or replaced anything yet. still need to use .fit() and .transform().

# Fit on training data only - # Learn medians from TRAINING data only
numeric_imputer.fit(X_train[numeric_columns])  # This line tells the imputer to learn the median value of each numeric column using only X_train.
# .fit() → calculates and stores the replacement values.
# X_train[numeric_columns] → selects only the numerical columns from your training dataset.
# .fit() → It does not replace the missing values yet. It only calculates and stores the medians.
# so:
    #   fit() → learn the median from training data only
    #   transform() → use those same medians to fill missing values in train, validation, and test data 


# Transform train, validation, and test - # Apply the same learned medians to all splits
X_train[numeric_columns] = numeric_imputer.transform(
    X_train[numeric_columns]
)

X_val[numeric_columns] = numeric_imputer.transform(
    X_val[numeric_columns]
)

X_test[numeric_columns] = numeric_imputer.transform(
    X_test[numeric_columns]
)

# error: there is a missed column in val & test sets (solved) :
    # actual_delivery_days
    # delivery_difference_days
    # customer_zip_code_prefix
    # seller_zip_code_prefix
    # seller_count
    # customer_seller_same_state
    # zip_prefix_difference

In [22]:
# verify that missing values are gone:
print("Train missing values:", X_train[numeric_columns].isna().sum().sum())
print("Validation missing values:", X_val[numeric_columns].isna().sum().sum())
print("Test missing values:", X_test[numeric_columns].isna().sum().sum())

# expected result:
    # Train missing values: 0
    # Validation missing values: 0
    # Test missing values: 0

Train missing values: 0
Validation missing values: 0
Test missing values: 0

In [18]:
# For categorical columns:
# recommend "Unknown" because missing itself may contain useful information.
    # SimpleImputer(strategy="most_frequent")
    #  or
    # SimpleImputer(strategy="constant", fill_value="Unknown")

# from sklearn.impute import SimpleImputer

# Create categorical imputer: creates an imputer for categorical columns (If a categorical column has missing values (NaN), it replaces them with Unknown)
categorical_imputer = SimpleImputer(
    strategy="constant", # Replace every missing value with one fixed value that you specify.
    fill_value="Unknown"
)

# Fit on training data only
# fit() should be done only on X_train, then use the same fitted imputer to transform validation and test data to avoid data leakage.
categorical_imputer.fit(X_train[categorical_columns])

# Apply to all splits
X_train[categorical_columns] = categorical_imputer.transform(
    X_train[categorical_columns]
)

X_val[categorical_columns] = categorical_imputer.transform(
    X_val[categorical_columns]
)

X_test[categorical_columns] = categorical_imputer.transform(
    X_test[categorical_columns]
)

In [19]:
# verify that missing values are gone:
print("Train missing:", X_train[categorical_columns].isna().sum().sum())
print("Validation missing:", X_val[categorical_columns].isna().sum().sum())
print("Test missing:", X_test[categorical_columns].isna().sum().sum())

# should get:
    # Train missing: 0
    # Validation missing: 0
    # Test missing: 0

Train missing: 0
Validation missing: 0
Test missing: 0

Encode categorical variables
--------

In [21]:
for col in categorical_columns:
    print(
        col,
        "→",
        X_train[col].nunique(),
        "unique values"
    )

order_id → 67533 unique values
customer_id → 67533 unique values
order_status → 2 unique values
customer_unique_id → 65962 unique values
customer_city → 3675 unique values
customer_state → 27 unique values
seller_state → 71 unique values

In [22]:
for col in categorical_columns:
    print(f"{col}: {X_train[col].nunique():,} unique values")

order_id: 67,533 unique values
customer_id: 67,533 unique values
order_status: 2 unique values
customer_unique_id: 65,962 unique values
customer_city: 3,675 unique values
customer_state: 27 unique values
seller_state: 71 unique values

In [23]:
# update the categorical_columns to avoid having high number of encoded columns
categorical_columns = [
    "order_status",
    "customer_city",
    "customer_state",
    "seller_state"
]

In [24]:
from sklearn.preprocessing import OneHotEncoder

# OneHotEncoder: It converts categorical values into numerical columns that machine learning models can use.
# handle_unknown="ignore" is important: if a new category appears in the validation or test set that was not present in the training set, 
    # the encoder will not raise an error.

# How it works
# For every categorical column:
    # Finds the unique categories in the training data.
    # Creates one new column for each category.
    # Puts 1 in the matching category column.
    # Puts 0 in all other category columns.
# The encoder learns categories only from X_train, and then the same learned columns are used to transform X_val and X_test.

# Create the encoder
categorical_encoder = OneHotEncoder(
    handle_unknown="ignore",  # important because validation or test data may contain categories that were not present in training.
    sparse_output=False
)

# sparse_output=False: Python gives you a normal table-like array (Give me the complete table.)
# sparse_output=True (default): Python stores the same information in a memory-saving sparse format, because there are lots of zeros. 
    # (Don't waste memory storing all those zeros.)

# The encoder must be fitted only on the training set.

# Fit ONLY on training data
categorical_encoder.fit(X_train[categorical_columns]) # Teach the OneHotEncoder what categories exist in each categorical column, 
                                                        # using only the training data.
                                                        # It does not change X_train. It only learns and remembers the categories.
                                                        # fit() is "learn"

# Transform all three datasets
X_train_encoded = categorical_encoder.transform(
    X_train[categorical_columns]
)

X_val_encoded = categorical_encoder.transform(
    X_val[categorical_columns]
)

X_test_encoded = categorical_encoder.transform(
    X_test[categorical_columns]
)

In [25]:
# Check the result 
print("Train encoded shape:", X_train_encoded.shape)
print("Validation encoded shape:", X_val_encoded.shape)
print("Test encoded shape:", X_test_encoded.shape)

Train encoded shape: (67533, 3775)
Validation encoded shape: (14471, 3775)
Test encoded shape: (14472, 3775)

In [26]:
# see the generated feature names: gets the names of all the new columns created by OneHotEncoder.
encoded_feature_names = categorical_encoder.get_feature_names_out(
    categorical_columns
)

print(encoded_feature_names)

['order_status_canceled' 'order_status_delivered'
 'customer_city_abadia dos dourados' ... 'seller_state_SP,RS'
 'seller_state_SP,SC' 'seller_state_SP,SE']

Scale numerical features
------

In [ ]:
# Scaling depends on the model.  
# For models such as:  
#     •	Logistic Regression  
#     •	KNN  
#     •	SVM  
#     •	Neural Networks  
# scaling is usually useful.  
# For tree-based models such as:  
#     •	Decision Tree  
#     •	Random Forest  
#     •	XGBoost  
#     •	LightGBM  
# scaling is generally not necessary.  
# Since we may compare multiple models later, we can initially build a preprocessing pipeline with scaling.

In [28]:
from sklearn.preprocessing import StandardScaler

# Create the scaler
numerical_scaler = StandardScaler()

# Fit it ONLY on the training data
numerical_scaler.fit(X_train[numeric_columns])
# This calculates the mean and standard deviation for every numerical feature using training data only.

# Transform all three datasets
X_train_scaled = numerical_scaler.transform(
    X_train[numeric_columns]
)

X_val_scaled = numerical_scaler.transform(
    X_val[numeric_columns]
)

X_test_scaled = numerical_scaler.transform(
    X_test[numeric_columns]
)

In [29]:
# Convert the scaled result back to DataFrames
X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=numeric_columns,
    index=X_train.index
)

X_val_scaled = pd.DataFrame(
    X_val_scaled,
    columns=numeric_columns,
    index=X_val.index
)

X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=numeric_columns,
    index=X_test.index
)

In [31]:
print(numeric_columns)

['number_of_items', 'total_freight_value', 'total_price', 'number_of_sellers', 'number_of_products', 'number_of_payments', 'total_payment_value', 'number_of_payment_types', 'max_payment_installments', 'purchase_year', 'purchase_month', 'purchase_dayofweek', 'purchase_hour', 'actual_delivery_days', 'estimated_delivery_days', 'delivery_difference_days', 'customer_zip_code_prefix', 'seller_zip_code_prefix', 'seller_count', 'customer_seller_same_state', 'zip_prefix_difference', 'purchase_day', 'approval_delay_hours']

In [32]:
print("Train scaled shape:", X_train_scaled.shape)
print("Validation scaled shape:", X_val_scaled.shape)
print("Test scaled shape:", X_test_scaled.shape)

Train scaled shape: (67533, 23)
Validation scaled shape: (14471, 23)
Test scaled shape: (14472, 23)

Build the preprocessing pipeline
-------

In [33]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [ ]:
# Numerical pipeline:
numeric_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]
)

# creates a two-step preprocessing pipeline.
    # Step 1 — Imputer: ("imputer", SimpleImputer(strategy="median"))
        # If a numerical feature has missing values: the imputer replaces NaN with the median of that column.
        # The median is calculated from training data when the pipeline is fitted.

    # Step 2 — Scaler: ("scaler", StandardScaler())
        # After missing values are handled, StandardScaler scales the numerical features.

In [35]:
# Categorical pipeline:
categorical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(
            strategy="constant",
            fill_value="Unknown"
        )),
        
        ("encoder", OneHotEncoder(
            handle_unknown="ignore"
        ))
    ]
)

In [ ]:
# Combine them:
# creates the main preprocessing object that combines numerical and categorical preprocessing.
preprocessor = ColumnTransformer( # combines columns
    transformers=[
        (
            "num",  # Take the columns listed in numerical_columns and send them through numeric_transformer.
            numeric_transformer,
            numeric_columns
        ),
        
        (
            "cat",  # Take the columns listed in categorical_columns and send them through categorical_transformer.
            categorical_transformer,
            categorical_columns
        )
    ]
)

In [ ]:
#                  X_train
#                     │
#           ┌─────────┴─────────┐
#           ↓                   ↓
#    Numerical columns     Categorical columns
#           │                   │
#           ↓                   ↓
# numeric_transformer   categorical_transformer
#           │                   │
#           ↓                   ↓
#  Impute + Scale       Impute + One-Hot Encode
#           │                   │
#           └─────────┬─────────┘
#                     ↓
#               Final features

Fit only on training data
------

In [23]:
# This is one of the most important parts of notebook.
X_train_processed = preprocessor.fit_transform(X_train)

# Then only transform validation and test:
X_val_processed = preprocessor.transform(X_val)

X_test_processed = preprocessor.transform(X_test)
# ----------------------------------------------------
# Never do this:
    # preprocessor.fit_transform(X_val)
# or:
    # preprocessor.fit_transform(X_test)
# That would cause data leakage.

In [24]:
print("Numeric columns:")
print(numeric_columns)

print("\nCategorical columns:")
print(categorical_columns)

print("\nProcessed shapes:")
print("Train:", X_train_processed.shape)
print("Validation:", X_val_processed.shape)
print("Test:", X_test_processed.shape)

Numeric columns:
['number_of_items', 'total_freight_value', 'total_price', 'number_of_sellers', 'number_of_products', 'number_of_payments', 'total_payment_value', 'number_of_payment_types', 'max_payment_installments', 'purchase_year', 'purchase_month', 'purchase_dayofweek', 'purchase_hour', 'estimated_delivery_days', 'customer_zip_code_prefix', 'seller_zip_code_prefix', 'seller_count', 'customer_seller_same_state', 'zip_prefix_difference', 'purchase_day', 'approval_delay_hours']

Categorical columns:
['order_status', 'customer_city', 'customer_state', 'seller_state']

Processed shapes:
Train: (67533, 3796)
Validation: (14471, 3796)
Test: (14472, 3796)

In [ ]:
from pathlib import Path

import joblib

MODELS_DIR = PROJECT_ROOT / "models"
preprocessor_path = MODELS_DIR / "preprocessor.joblib"

loaded_preprocessor = joblib.load(preprocessor_path)

print("Loaded:", type(loaded_preprocessor))
print("Feature count:", len(loaded_preprocessor.get_feature_names_out()))

Loaded: <class 'sklearn.compose._column_transformer.ColumnTransformer'>
Feature count: 3796

Get the final feature names
------

In [40]:
# After one-hot encoding, number of features will increase.
# For example:
    # seller_state
        # might become:
            # seller_state_SP
            # seller_state_RJ
            # seller_state_MG
            # seller_state_PR


# Get all final feature names:
feature_names = preprocessor.get_feature_names_out()

display(feature_names[:20])
# Check the total:
len(feature_names)

array(['num__number_of_items', 'num__total_freight_value',
       'num__total_price', 'num__number_of_sellers',
       'num__number_of_products', 'num__number_of_payments',
       'num__total_payment_value', 'num__number_of_payment_types',
       'num__max_payment_installments', 'num__purchase_year',
       'num__purchase_month', 'num__purchase_dayofweek',
       'num__purchase_hour', 'num__actual_delivery_days',
       'num__estimated_delivery_days', 'num__delivery_difference_days',
       'num__customer_zip_code_prefix', 'num__seller_zip_code_prefix',
       'num__seller_count', 'num__customer_seller_same_state'],
      dtype=object)

3798

Convert the processed data into DataFrames
--------

In [41]:
# This makes the data easier to inspect.

X_train_final = pd.DataFrame(
    X_train_processed.toarray()
    if hasattr(X_train_processed, "toarray")
    else X_train_processed,
    
    columns=feature_names,
    index=X_train.index
)

In [42]:
# Do the same:
X_val_final = pd.DataFrame(
    X_val_processed.toarray()
    if hasattr(X_val_processed, "toarray")
    else X_val_processed,
    
    columns=feature_names,
    index=X_val.index
)
X_test_final = pd.DataFrame(
    X_test_processed.toarray()
    if hasattr(X_test_processed, "toarray")
    else X_test_processed,
    
    columns=feature_names,
    index=X_test.index
)

In [43]:
# Check: All three should have the same number of columns.
print(X_train_final.shape)
print(X_val_final.shape)
print(X_test_final.shape)

(67533, 3798)
(14471, 3798)
(14472, 3798)

Final feature table
------

In [ ]:
# create the processed feature matrices:
X_train_processed = preprocessor.transform(X_train)
X_val_processed = preprocessor.transform(X_val)
X_test_processed = preprocessor.transform(X_test)

In [ ]:
# verify:
print("Train:", X_train_processed.shape)
print("Validation:", X_val_processed.shape)
print("Test:", X_test_processed.shape)

Save the fitted preprocessing object (the fitted transformers)
-------

In [ ]:
# preprocessor is not a normal table, preprocessor is a Python/scikit-learn object containing things like:
#     median values learned by SimpleImputer
#     category mappings learned by OneHotEncoder
#     means and standard deviations learned by StandardScaler
#     column ordering and preprocessing configuration

# It is not naturally a DataFrame/table.

In [ ]:
# This is essential for production.
# Create a folder:
# from pathlib import Path

# import joblib

# # Create artifacts folder
# Path("artifacts").mkdir(exist_ok=True)


# # Save the preprocessor:
# joblib.dump(
#     preprocessor,
#     "artifacts/preprocessor.joblib"
# )

# This contains your fitted:

#     numerical imputer
#     numerical scaler
#     categorical imputer
#     OneHotEncoder
#     column configuration
# ------------------------------------------------------------
# Later, in production:
    # preprocessor = joblib.load(
    #     "artifacts/preprocessor.joblib"
    # )
# Then:
    # new_data_processed = preprocessor.transform(new_data)
# You do not fit again.

from pathlib import Path

import joblib

MODELS_DIR = PROJECT_ROOT / "models"
MODELS_DIR.mkdir(parents=True, exist_ok=True)

preprocessor_path = MODELS_DIR / "preprocessor.joblib"

joblib.dump(
    preprocessor,
    preprocessor_path,
)

print("Saved:", preprocessor_path)

['artifacts/preprocessor.joblib']

In [ ]:
loaded_preprocessor = joblib.load(preprocessor_path)

print("Loaded:", type(loaded_preprocessor))
print("Feature count:", len(loaded_preprocessor.get_feature_names_out()))

In [46]:
print("Train processed shape:", X_train_processed.shape)
print("Validation processed shape:", X_val_processed.shape)
print("Test processed shape:", X_test_processed.shape)

Train processed shape: (67533, 3798)
Validation processed shape: (14471, 3798)
Test processed shape: (14472, 3798)

Save the feature list
------

In [47]:
# Save the feature list
feature_names = preprocessor.get_feature_names_out()

print(f"Number of processed features: {len(feature_names)}")
print(feature_names[:20])

Number of processed features: 3798
['num__number_of_items' 'num__total_freight_value' 'num__total_price'
 'num__number_of_sellers' 'num__number_of_products'
 'num__number_of_payments' 'num__total_payment_value'
 'num__number_of_payment_types' 'num__max_payment_installments'
 'num__purchase_year' 'num__purchase_month' 'num__purchase_dayofweek'
 'num__purchase_hour' 'num__actual_delivery_days'
 'num__estimated_delivery_days' 'num__delivery_difference_days'
 'num__customer_zip_code_prefix' 'num__seller_zip_code_prefix'
 'num__seller_count' 'num__customer_seller_same_state']

In [48]:
# Save the feature list
import json

feature_names = preprocessor.get_feature_names_out()

with open("artifacts/feature_names.json", "w") as f:
    json.dump(feature_names.tolist(), f, indent=2)

Recommended Notebook 5 flow
-----

1. Load training, validation, and test sets  

2. Check available columns  

3. Remove:  
   - Target  
   - IDs  
   - Future/leakage columns  

4. Create prediction-time features:  
   - Date features  
   - Estimated delivery duration  
   - Approval delay  
   - Geographic features  
   - Aggregated order features  

5. Apply the same feature engineering function  
   to Train / Validation / Test  

6. Identify:  
   - Numerical features  
   - Categorical features  

7. Build preprocessing pipelines  

8. FIT on Train only  

9. TRANSFORM Validation and Test  

10. Create final feature tables  

11. Save:  
    - preprocessor.joblib  
    - feature_names.joblib  
    - final feature tables  

12. Verify:  
    - Same columns  
    - No unexpected missing values  
    - No target leakage

recommendation for your next step  
Before writing the complete Notebook 5 code, print the current columns of training_set again. Then we can decide exactly which columns to keep, drop, and transform based on the features you created in Notebook 4.  

That is safer than using a generic pipeline, especially because your Olist ML table has already been aggregated and some columns such as seller information are not present.

TESTIND
---------

In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
SRC_PATH = PROJECT_ROOT / "src"

In [2]:
sys.path.insert(
    0,
    str(SRC_PATH)
)

In [3]:
print("Project root:", PROJECT_ROOT)
print("Source path:", SRC_PATH)
print("Source exists:", SRC_PATH.exists())

Project root: d:\Zain MS\Programming\Machine Learning\Qafza_MLOps\closed Tasks\Task_3\olist-mlops
Source path: d:\Zain MS\Programming\Machine Learning\Qafza_MLOps\closed Tasks\Task_3\olist-mlops\src
Source exists: True

In [6]:
import features

print(features)
print(getattr(features, "__file__", None))

<module 'features' from 'd:\\Zain MS\\Programming\\Machine Learning\\Qafza_MLOps\\closed Tasks\\Task_3\\olist-mlops\\src\\features.py'>
d:\Zain MS\Programming\Machine Learning\Qafza_MLOps\closed Tasks\Task_3\olist-mlops\src\features.py

In [ ]:
from features.feature_engineering import create_date_features

In [10]:
# test_df = updated_training_set.head(5)

# test_result = create_date_features(test_df)

# print(test_result.shape)
# print(test_result.columns.tolist())


import pandas as pd

test_df = pd.DataFrame({
    "order_purchase_timestamp": ["2026-01-01 10:00:00"],
    "order_approved_at": ["2026-01-01 12:00:00"],
    "order_estimated_delivery_date": ["2026-01-10 00:00:00"],
})

test_result = create_date_features(test_df)

print(test_result)

  order_purchase_timestamp   order_approved_at order_estimated_delivery_date  \
0      2026-01-01 10:00:00 2026-01-01 12:00:00                    2026-01-10

   purchase_year  purchase_month  purchase_day  purchase_dayofweek  \
0           2026               1             1                   3

   purchase_hour  estimated_delivery_days  approval_delay_hours
0             10                 8.583333                   2.0